<a href="https://www.kaggle.com/code/utkarshx27/backpack-prediction-autoviz-xgb?scriptVersionId=220294327" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [7]:
!pip install autoviz

Collecting autoviz
  Downloading autoviz-0.1.905-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: xlrd in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.0.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.9.4)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.14.0)
Collecting pyamg (from autoviz)
  Downloading pyamg-5.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.2.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.14.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from autoviz) (3.2.4)
Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (from autoviz) (0.17.1)
Collecting xgboost<1.7,>=0.82 (from autoviz)
  Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from autoviz) (2024.9.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from autoviz) (4.12.2)
Collecting pandas-dq>=1.29 (from autoviz)
  Downloading pandas_dq-1.29-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.26.4)
Collecting hvplot>=0.9.2 (from autoviz)
  Downloading hvplot-0.11.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.20.0)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (1.5.4)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.10/dist-packages (from autoviz) (2.2.2)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.10/dist-packages (from autoviz) (3.7.5)
Collecting seaborn>0.12.2 (from autoviz)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.6.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (24.2)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (2.2.0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>3.7.4->autoviz) (2.8.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.24.0->autoviz) (2.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0->autoviz) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0->autoviz) (2024.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (6.2.0)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (2.0.3)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (3.7)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (3.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (0.4.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from panel>=1.4.0->autoviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->autoviz) (3.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from nltk->autoviz) (1.17.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels->autoviz) (1.0.1)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.4)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.2)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.3.3)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.10/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2024.9.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.10/dist-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.24.0->autoviz) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.24.0->autoviz) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.24.0->autoviz) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.24.0->autoviz) (2024.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=1.4.0->autoviz) (2024.12.14)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.24.0->autoviz) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.2)
Downloading autoviz-0.1.905-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 2.6 MB/s eta 0:00:00
Downloading hvplot-0.11.2-py3-none-any.whl (161 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.9/161.9 kB 6.3 MB/s eta 0:00:00
Downloading pandas_dq-1.29-py3-none-any.whl (29 kB)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 10.1 MB/s eta 0:00:00
Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl (255.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 5.9 MB/s eta 0:00:000:00:0100:01
Downloading pyamg-5.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 53.1 MB/s eta 0:00:00:00:01
Installing collected packages: xgboost, seaborn, pyamg, pandas-dq, hvplot, autoviz
  Attempting uninstall: xgboost
    Found existing installation: xgboost 2.0.3
    Uninstalling xgboost-2.0.3:
      Successfully uninstalled xgboost-2.0.3
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.12.2
    Uninstalling seaborn-0.12.2:
      Successfully uninstalled seaborn-0.12.2
Successfully installed autoviz-0.1.905 hvplot-0.11.2 pandas-dq-1.29 pyamg-5.2.1 seaborn-0.13.2 xgboost-1.6.2

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from autoviz import data_cleaning_suggestions
from autoviz import AutoViz_Class

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [19]:
train = pd.read_csv("/kaggle/input/playground-series-s5e2/train.csv")
test = pd.read_csv("/kaggle/input/playground-series-s5e2/test.csv")
sub = pd.read_csv("/kaggle/input/playground-series-s5e2/sample_submission.csv")

In [9]:
data_cleaning_suggestions(train)

    All variables classified into correct types.

,Data Type,Missing Values%,Unique Values%,Minimum Value,Maximum Value,DQ Issue
id,int64,0.000000,100,0.0,299999.0,Possible ID column: drop before modeling step.
Brand,object,3.235000,0,,,"9705 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Material,object,2.782333,0,,,"8347 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Size,object,2.198333,0,,,"6595 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Compartments,float64,0.000000,NA,1.0,10.0,No issue
Laptop Compartment,object,2.481333,0,,,"7444 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Waterproof,object,2.350000,0,,,"7050 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Style,object,2.656667,0,,,"7970 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Color,object,3.316667,0,,,"9950 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Weight Capacity (kg),float64,0.046000,NA,5.0,30.0,"138 missing values. Impute them with mean, median, mode, or a constant value such as 123."
Price,float64,0.000000,NA,15.0,150.0,No issue

In [10]:
data_cleaning_suggestions(test)

    All variables classified into correct types.

,Data Type,Missing Values%,Unique Values%,Minimum Value,Maximum Value,DQ Issue
id,int64,0.0000,100,300000.0,499999.0,Possible ID column: drop before modeling step.
Brand,object,3.1135,0,,,"6227 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Material,object,2.8065,0,,,"5613 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Size,object,2.1905,0,,,"4381 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Compartments,float64,0.0000,NA,1.0,10.0,No issue
Laptop Compartment,object,2.4810,0,,,"4962 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Waterproof,object,2.4055,0,,,"4811 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Style,object,2.5765,0,,,"5153 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Color,object,3.3925,0,,,"6785 missing values. Impute them with mean, median, mode, or a constant value such as 123., Mixed dtypes: has 2 different data types: object, float,"
Weight Capacity (kg),float64,0.0385,NA,5.0,30.0,"77 missing values. Impute them with mean, median, mode, or a constant value such as 123."

In [22]:
train_df = train.copy(deep=True)
#test_df = test.copy(deep=True)
train_df.drop(columns=['id'], inplace=True)
categorical_cols = train_df.select_dtypes(include=['object']).columns
train_df[categorical_cols] = train_df[categorical_cols].astype('category')

X = train_df.drop(columns=['Price'])
y = train_df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
space = {
    'max_depth': hp.quniform("max_depth", 3, 18, 1),
    'gamma': hp.uniform('gamma', 1, 9),
    'reg_alpha': hp.quniform('reg_alpha', 40, 180, 1),
    'reg_lambda': hp.uniform('reg_lambda', 0, 1),
    'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 1),
    'min_child_weight': hp.quniform('min_child_weight', 0, 10, 1),
    'n_estimators': 180,
    'seed': 0
}

def objective(space):
    clf = xgb.XGBRegressor(
        n_estimators=int(space['n_estimators']),
        max_depth=int(space['max_depth']),
        gamma=space['gamma'],
        reg_alpha=int(space['reg_alpha']),
        reg_lambda=space['reg_lambda'],
        min_child_weight=int(space['min_child_weight']),
        colsample_bytree=space['colsample_bytree'],
        objective='reg:squarederror',
        enable_categorical=True
    )

    clf.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric="rmse", early_stopping_rounds=10, verbose=False)
    
    y_pred = clf.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    
    print(f"RMSE: {rmse:.4f}")
    return {'loss': rmse, 'status': STATUS_OK}

trials = Trials()
best_hyperparams = fmin(fn=objective, space=space, algo=tpe.suggest, max_evals=100, trials=trials)

In [27]:
print("\nBest Hyperparameters:", best_hyperparams)

Best Hyperparameters: {'colsample_bytree': 0.6883467648813073, 'gamma': 8.535942018519794, 'max_depth': 3.0, 'min_child_weight': 2.0, 'reg_alpha': 61.0, 'reg_lambda': 0.9857976546678712}

In [30]:
test_df = test.copy(deep=True)
test_df.drop(columns=['id'], inplace=True)

categorical_cols = test_df.select_dtypes(include=['object']).columns
test_df[categorical_cols] = test_df[categorical_cols].astype('category')

X_train = train_df.drop(columns=['Price'])
y_train = train_df['Price']
X_test = test_df

best_params = {
    'n_estimators': 180,
    'max_depth': int(3),
    'gamma': 8.535942018519794,
    'reg_alpha': int(61),
    'reg_lambda': 0.9857976546678712,
    'min_child_weight': int(2),
    'colsample_bytree': 0.6883467648813073,
    'objective': 'reg:squarederror',
    'enable_categorical': True,
    'random_state': 42
}

model = xgb.XGBRegressor(**best_params)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

sub['Price'] = y_pred
sub.to_csv("submission.csv", index=False)